version: 2.1

jobs:

    test:

      docker:

        - image: cimg/openjdk:18.0.2

      steps:

        - checkout

        - run:

            name: Change directory

            command: ls -a

        - run:

            name: Execute IaC Scan

            command: java -jar demo1.jar com.example.demo.DemoApplication

workflows:

      test: 

        jobs:

          - test
